#include "include/keyboard.h"

char translate_ps2_scancode_to_char(unsigned char scancode){
    switch(scancode){
        case 0x02:
            return '1';
        case 0x03:
            return '2';
        case 0x04:
            return '3';
        case 0x05:
            return '4';
        case 0x06:
            return '5';
        case 0x07:
            return '6';
        case 0x08:
            return '7';
        case 0x09:
            return '8';
        case 0x0A:
            return '9';
        case 0x0B:
            return '0';
        case 0x0C:
            return '-';
        case 0x0D:
            return '=';
        case 0x0E:
            return '\b';
        case 0x0F:
            return '\t';
        case 0x10:
            return 'q';
        case 0x11:
            return 'w';
        case 0x12:
            return 'e';
        case 0x13:
            return 'r';
        case 0x14:
            return 't';
        case 0x15:
            return 'y';
        case 0x16:
            return 'u';
        case 0x17:
            return 'i';
        case 0x18:
            return 'o';
        case 0x19:
            return 'p';
        case 0x1A:
            return '[';
        case 0x1B:
            return ']';
        case 0x1C:
            return '\n';
        case 0x1E:
            return 'a';
        case 0x1F:
                return 's';
        case 0x20:
            return 'd';
        case 0x21:
            return 'f';
        case 0x22:
            return 'g';
        case 0x23:
            return 'h';
        case 0x24:
            return 'j';
        case 0x25:
            return 'k';
        case 0x26:
            return 'l';
        case 0x27:
            return ';';
        case 0x28:
            return '\'';
        case 0x29:
            return '`';
        case 0x2B:
            return '\\';
        case 0x2C:
            return 'z';
        case 0x2D:
            return 'x';
        case 0x2E:
            return 'c';
        case 0x2F:
            return 'v';
        case 0x30:
            return 'b';
        case 0x31:
            return 'n';
        case 0x32:
            return 'm';
        case 0x33:
            return ',';
        case 0x34:
            return '.';
        case 0x35:
            return '/';
        case 0x37:
            return '*';
        case 0x39:
            return ' ';
        case 0x47:
            return '7';
        case 0x48:
            return '8';
        case 0x49:
            return '9';
        case 0x4A:
            return '-';
        case 0x4B:
            return '4';
        case 0x4C:
            return '5';
        case 0x4D:
            return '6';
        case 0x4E:
            return '+';
        case 0x4F:
            return '1';
        case 0x50:
            return '2';
        case 0x51:
            return '3';
        case 0x52:
            return '0';
        
        // do the same but with negative values so we know they are released
        case 0x82:
            return -'1';
        case 0x83:
            return -'2';
        case 0x84:
            return -'3';
        case 0x85:
            return -'4';
        case 0x86:
            return -'5';
        case 0x87:
            return -'6';
        case 0x88:
            return -'7';
        case 0x89:
            return -'8';
        case 0x8A:
            return -'9';
        case 0x8B:
            return -'0';
        case 0x8C:
            return -'-';
        case 0x8D:
            return -'=';
        case 0x8E:
            return -'\b';
        case 0x8F:
            return -'\t';
        case 0x90:
            return -'q';
        case 0x91:
            return -'w';
        case 0x92:
            return -'e';
        case 0x93:
            return -'r';
        case 0x94:
            return -'t';
        case 0x95:
            return -'y';
        case 0x96:
            return -'u';
        case 0x97:
            return -'i';
        case 0x98:
            return -'o';
        case 0x99:
            return -'p';
        case 0x9A:
            return -'[';
        case 0x9B:
            return -']';
        case 0x9C:
            return -'\n';
        case 0x9E:
            return -'a';
        case 0x9F:
            return -'s';
        case 0xA0:
            return -'d';
        case 0xA1:
            return -'f';
        case 0xA2:
            return -'g';
        case 0xA3:
            return -'h';
        case 0xA4:
            return -'j';
        case 0xA5:
            return -'k';
        case 0xA6:
            return -'l';
        case 0xA7:
            return -';';
        case 0xA8:
            return -'\'';
        case 0xA9:
            return -'`';
        case 0xAB:
            return -'\\';
        case 0xAC:
            return -'z';
        case 0xAD:
            return -'x';
        case 0xAE:
            return -'c';
        case 0xAF:
            return -'v';
        case 0xB0:
            return -'b';
        case 0xB1:
            return -'n';
        case 0xB2:
            return -'m';
        case 0xB3:
            return -',';
        case 0xB4:
            return -'.';
        case 0xB5:
            return -'/';
        case 0xB7:
            return -'*';
        case 0xB9:
            return -' ';
        case 0xC7:
            return -'7';
        case 0xC8:
            return -'8';
        case 0xC9:
            return -'9';
        case 0xCA:
            return -'-';
        case 0xCB:
            return -'4';
        case 0xCC:
            return -'5';
        case 0xCD:
            return -'6';
        case 0xCE:
            return -'+';
        case 0xCF:
            return -'1';
        case 0xD0:
            return -'2';
        case 0xD1:
            return -'3';
        case 0xD2:
            return -'0';
        case 0xD3:
            return -'.';
        default:
            return 0;
    }
};